### ISSUE TITLE
Recover inhibitory connections

### ISSUE THREAD

**Issue by nfzd** [fzenke/pub2015orchestrated#2]
Hi,
I am trying to unpack the weight matrices from the simulation results for some analysis. The EE weights are stored and I can load them (the jupyter notebook is very helpful for this). But I cannot find the EI, IE, and II weights anywhere. Are they not stored by the simulation code?
Thanks a lot.

**Comment by fzenke** [comment]
This is where the weights are stored: https://github.com/fzenke/pub2015orchestrated/blob/master/src/sim_rc_p10c.cpp#L799
Looks like it's only EE that's stored, but you can copy and paste (and adapt) these two lines for the other weight matrices.
